site_name: wenlin的博客
repo_name: wenlin-gk.github.io
# 右上角图标的链接
repo_url: https://github.com/wenlin-gk/wenlin-gk.github.io
# 主页的链接
site_url: https://wenlin-gk.github.io
# 页面链接的前缀
edit_uri: /wenlin-gk/wenlin-gk.github.io/tree/master/
site_author: wenlin

# # 记录用户访问信息
# google_analytics:
#   - 'UA-XXXXXXXX-X'
#   - 'auto'

nav:
  # - 规范理论:
  #   - 网络:
  #     - 计算机网络基础.md
  #     - 网络相关应用以及问题.md
  #   - 通用: 通用.md
  - Resume.md
  - 思考人生.md

# ================
theme:
  name: material
  logo: img/favicon.ico
  favicon: img/favicon.ico
  language: zh
  # 不使用google字体
  # font: false
  font:
    text: 'Roboto'
    code: 'Inconsolata'
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
#extra:
#  disqus: wenlin-gk
# # ================
# theme:
#   name: readthedocs
# # ================
# theme:
#   name: windmill
# # ================
# theme:
#   name: ivory
